"""
Django settings for weeb_api project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from datetime import timedelta
from utils.utils import env_int

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Load the .env file located next to manage.py
load_dotenv(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG").lower() == "true"

# Application definition

INSTALLED_APPS = [
    'corsheaders',
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "pwned_passwords_django",
    'rest_framework_simplejwt.token_blacklist',
    "axes",
    "users",
    "monitoring",
    "contact",
    "articles",
    "ml",
    'rest_framework',
]

# Secret key for development. DO NOT USE in production.
SECRET_KEY = os.environ.get('SECRET_KEY')

# Use the custom user model by default
AUTH_USER_MODEL = "users.CustomUser"


###############################
# Jason Web Token configuration
###############################

ACCESS_MIN = env_int("ACCESS_TOKEN_LIFETIME")
REFRESH_DAYS = env_int("REFRESH_TOKEN_LIFETIME")
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=ACCESS_MIN),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=REFRESH_DAYS),
    
    # Each refresh issues a new refresh token as well
    "ROTATE_REFRESH_TOKENS": os.getenv("ROTATE_REFRESH_TOKENS"),
    "BLACKLIST_AFTER_ROTATION": os.getenv("BLACKLIST_AFTER_ROTATION")
}

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 9,
    'DEFAULT_FILTER_BACKENDS': [
        'rest_framework.filters.OrderingFilter',
        'rest_framework.filters.SearchFilter',
    ]
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    "django.middleware.security.SecurityMiddleware",
    'whitenoise.middleware.WhiteNoiseMiddleware',
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "axes.middleware.AxesMiddleware"
]

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '').split(',')

# CORS allowed origins for frontend apps (development)
CORS_ALLOWED_ORIGINS = os.environ.get('CORS_ALLOWED_ORIGINS', '').split(',')

CORS_ALLOW_CREDENTIALS = True

ROOT_URLCONF = "weeb_api.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "weeb_api.wsgi.application"

# -------------------------------------------------------------------
# django-axes configuration
# (https://django-axes.readthedocs.io/) used to limit password-based
# login attempts (brute-force protection).
# -------------------------------------------------------------------
# Maximum number of failed login attempts before temporarily blocking
# the user/IP.
AXES_FAILURE_LIMIT = env_int("AXES_FAILURE_LIMIT")

# Time window during which failures are counted, in seconds.
# Example: 300 seconds = 5 minutes. After this window, the counter resets.
AXES_COOLOFF_TIME = env_int("AXES_COOLOFF_TIME") 

# Axes reads the email field as the login identifier in place of username
AXES_USERNAME_FORM_FIELD = os.getenv("AXES_USERNAME_FORM_FIELD") 

# Parameters used to identify a unique login attempt.
# Here: combination of IP address and username (email/username).
# A user is blocked only if the same IP + username fails N times within the window.
# Attempts from a different IP against the same username do not count toward the block
# for the original IP — mitigating targeted lockouts by third parties.
AXES_LOCKOUT_PARAMETERS = os.environ.get('AXES_LOCKOUT_PARAMETERS', '').split(',')

# Whether the lockout is automatically lifted after AXES_COOLOFF_TIME elapses.
# True = the user can retry after 5 minutes,
# False = an admin must manually unlock the account.
AXES_RESET_COOL_OFF = os.getenv("AXES_RESET_COOL_OFF") 
AXES_RESET_ON_SUCCESS = os.getenv("AXES_RESET_ON_SUCCESS") 

# Local development allowances
AXES_NEVER_LOCKOUT_WHITELIST = os.getenv("AXES_NEVER_LOCKOUT_WHITELIST") 
AXES_IP_WHITELIST = os.environ.get('AXES_IP_WHITELIST', '').split(',')


AUTHENTICATION_BACKENDS = [
    "axes.backends.AxesStandaloneBackend",   
    "django.contrib.auth.backends.ModelBackend",
]


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    # Prevents passwords too similar to user attributes (first name, last name, email, username)
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    
    # Enforces a minimum length of 14 characters for stronger passwords
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        'OPTIONS': {
            'min_length': 14,
        }
    },
    
    # Rejects common passwords listed in Django's internal list
    # (e.g., "password", "123456", etc.)
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    
    # Checks the password against databases of compromised passwords
    # via HaveIBeenPwned (k-anonymity API).
    {
        "NAME": "pwned_passwords_django.validators.PwnedPasswordsValidator"
    },
    
    # Rejects purely numeric passwords (e.g., "123456789")
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

USE_TZ = True
TIME_ZONE = "Europe/Paris"
LANGUAGE_CODE = "fr"
USE_I18N = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

REST_FRAMEWORK = {
    # Custom exception handling
    "EXCEPTION_HANDLER": "weeb_api.core.exceptions.custom_exception_handler",
    
    # Force JSON-only responses
    "DEFAULT_RENDERER_CLASSES": (
        "rest_framework.renderers.JSONRenderer",
    ),
    
    # Use JWT (SimpleJWT) as the default authentication method
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    
    # DRF throttling applied to all views
    "DEFAULT_THROTTLE_CLASSES": [
        # Rate limit for unauthenticated users
        "rest_framework.throttling.AnonRateThrottle",
        # Rate limit for authenticated users
        "rest_framework.throttling.UserRateThrottle",
        # Global rate limit per IP
        "weeb_api.core.throttles.SiteWideIPThrottle",
    ],

    "DEFAULT_THROTTLE_RATES": {
        # Unauthenticated users: max 60 requests per minute
        "anon": os.getenv("THROTTLE_ANON"),
        # Authenticated users: max 120 requests per minute
        "user": os.getenv("THROTTLE_USER"),
        # Global per IP (all requests combined): max 200 requests per minute
        "sitewide_ip": os.getenv("THROTTLE_SITEWIDE"),
    },
}
