"""
Django settings for weeb_api project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from datetime import timedelta
from utils.utils import env_int, env_bool

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# charge le .env qui est à côté de manage.py
load_dotenv(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# Application definition

INSTALLED_APPS = [
    'corsheaders',
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "pwned_passwords_django",
    'rest_framework_simplejwt.token_blacklist',
    "axes",
    "users",
    "contact",
    "articles",
    "ml",
    'rest_framework',
]

# Nouveau modèle d'utilisateur géré par défaut par Django
AUTH_USER_MODEL = "users.CustomUser"


###############################
# Jason Web Token configuration
###############################

ACCESS_MIN = env_int("ACCESS_TOKEN_LIFETIME")
REFRESH_DAYS = env_int("REFRESH_TOKEN_LIFETIME")
SIMPLE_JWT = {
    # "ACCESS_TOKEN_LIFETIME": timedelta(minutes=ACCESS_MIN),
    # "REFRESH_TOKEN_LIFETIME": timedelta(days=REFRESH_DAYS),
    "ACCESS_TOKEN_LIFETIME": timedelta(seconds=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    
    # chaque rafraîchissement renvoie également un nouveau refresh_token
    "ROTATE_REFRESH_TOKENS": os.getenv("ROTATE_REFRESH_TOKENS"),
    "BLACKLIST_AFTER_ROTATION": os.getenv("BLACKLIST_AFTER_ROTATION")
}

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 9,
    'DEFAULT_FILTER_BACKENDS': [
        'rest_framework.filters.OrderingFilter',
        'rest_framework.filters.SearchFilter',
    ]
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "axes.middleware.AxesMiddleware"
]

CORS_ALLOWED_ORIGINS = [ 
    "http://localhost:3000",
]

CORS_ALLOW_CREDENTIALS = True

ROOT_URLCONF = "weeb_api.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "weeb_api.wsgi.application"

# -------------------------------------------------------------------
# Configuration de la librairie django-axes
# (https://django-axes.readthedocs.io/) utilisée pour limiter
# les tentatives de connexion par mot de passe (brute-force protection).
# -------------------------------------------------------------------
# Nombre maximum de tentatives de connexion échouées
# avant de bloquer temporairement l’utilisateur/IP.
AXES_FAILURE_LIMIT = env_int("AXES_FAILURE_LIMIT")

# Durée pendant laquelle les échecs sont comptabilisés, en secondes.
# Ici : 300 secondes = 5 minutes. Après ce délai, le compteur repart à zéro.
AXES_COOLOFF_TIME = env_int("AXES_COOLOFF_TIME") 

# Axes lit l'email comme identifiant de connexion qui prend alors la place du username
AXES_USERNAME_FORM_FIELD = os.getenv("AXES_USERNAME_FORM_FIELD") 

# Paramètres pris en compte pour identifier une tentative de connexion unique.
# Ici : combinaison de l’adresse IP et du nom d’utilisateur (email/username).
# Un utilisateur sera bloqué uniquement si une même combinaison IP + username échoue 3 fois en 5 min.
# Si quelqu’un essaie de forcer le compte alice@example.com depuis une autre IP, cela ne comptera pas dans les tentatives de blocage de l’IP de Alice.
# => Cela évite qu’un attaquant sur une autre IP bloque un compte légitime.
AXES_LOCKOUT_PARAMETERS = os.environ.get('AXES_LOCKOUT_PARAMETERS', '').split(',')

# Indique si le blocage doit se lever automatiquement une fois
# le délai AXES_COOLOFF_TIME écoulé.
# True = l’utilisateur peut réessayer après 5 minutes,
# False = un admin doit débloquer manuellement.
AXES_RESET_COOL_OFF = os.getenv("AXES_RESET_COOL_OFF") 
AXES_RESET_ON_SUCCESS = os.getenv("AXES_RESET_ON_SUCCESS") 

# Pour pouvoir travailler en local
AXES_NEVER_LOCKOUT_WHITELIST = os.getenv("AXES_NEVER_LOCKOUT_WHITELIST") 
#AXES_IP_WHITELIST = os.environ.get('AXES_IP_WHITELIST', '').split(',')


AUTHENTICATION_BACKENDS = [
    "axes.backends.AxesStandaloneBackend",   
    "django.contrib.auth.backends.ModelBackend",
]


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    # Empêche d’utiliser un mot de passe trop proche des attributs de l’utilisateur
    # (ex. prénom, nom, email, username)
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    
    # Impose une longueur minimale de 14 caractères pour renforcer la robustesse
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        'OPTIONS': {
            'min_length': 14,
        }
    },
    
    # Refuse les mots de passe trop courants listés dans le fichier interne de Django
    # (ex. "password", "123456", "azerty", etc.)
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    
    # Vérifie que le mot de passe n’est pas présent dans les bases de données
    # de mots de passe compromis (via l’API HaveIBeenPwned en k-anonymity).
    # (ex. "football2018", "letmein123", etc.)
    {
        "NAME": "pwned_passwords_django.validators.PwnedPasswordsValidator"
    },
    
    # Refuse les mots de passe purement numériques (ex. "123456789")
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "fr"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

REST_FRAMEWORK = {
    # Gestions customisées des erreurs
    "EXCEPTION_HANDLER": "weeb_api.core.exceptions.custom_exception_handler",
    
    # Forcer les réponses au format JSON uniquement
    "DEFAULT_RENDERER_CLASSES": (
        "rest_framework.renderers.JSONRenderer",
    ),
    
    # Utiliser JWT (SimpleJWT) comme méthode d’authentification par défaut
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    
    # Throttles appliqués à toutes les vues DRF
    "DEFAULT_THROTTLE_CLASSES": [
        # Limite spécifique aux utilisateurs non authentifiés
        "rest_framework.throttling.AnonRateThrottle",
        # Limite spécifique aux utilisateurs authentifiés
        "rest_framework.throttling.UserRateThrottle",
        # Limite globale par adresse IP
        "weeb_api.core.throttles.SiteWideIPThrottle",
    ],

    "DEFAULT_THROTTLE_RATES": {
        # Utilisateurs non authentifiés : max 60 requêtes par minute
        "anon": os.getenv("THROTTLE_ANON"),
        # Utilisateurs authentifiés : max 120 requêtes par minute
        "user": os.getenv("THROTTLE_USER"),
        # Par IP (global, tous types de requêtes confondus) : max 200 requêtes par minute, pour
        "sitewide_ip": os.getenv("THROTTLE_SITEWIDE"),
    },
}