# Generated by Django 5.2.1 on 2025-09-12 13:08

import articles.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("author", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "publication_date",
                    models.DateField(default=articles.models.get_today_date),
                ),
            ],
        ),
    ]
